[package]
authors = ["Avery Harnish <averyharnish@gmail.com>"]
edition = "2021"
name = "xtask"
version = "0.1.0"

[dependencies]
anyhow = "1"
ansi_term = "0.12"
camino = "1"
lazy_static = "1"
structopt = { version = "0.3", default-features = false }
which = "4.2"